name: "Pironman 5 Mini"
description: "Pironman 5 Mini support"
version: "1.0.1"
slug: "pironman5-mini"
# image: "sunfounder/{arch}-pironman5-mini"
init: false
arch:
  - aarch64
startup: application
privileged:
  - SYS_RAWIO
  - SYS_ADMIN
gpio: true
devices:
  - /dev/i2c-1
  - /dev/spidev0.0
  - /dev/mem
hassio_api: true
hassio_role: "manager"
map:
 - addon_config:rw
environment:
  BLINKA_FORCECHIP: "BCM2XXX"
webui: "http://[HOST]:[PORT:34001]"
ports: 
  34001/tcp: 34001
ports_description:
  34001/tcp: Pironman 5 Mini Dashboard
panel_icon: mdi:view-dashboard
ingress: true
ingress_port: 34001